# Generated by Django 4.1.2 on 2022-10-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.AddField(
            model_name='category',
            name='cards',
            field=models.ManyToManyField(to='words.card'),
        ),
    ]
