# Generated by Django 4.1.2 on 2022-10-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_card_delete_word_category_cards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
