# Generated by Django 4.1.2 on 2022-10-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-gradelevel']},
        ),
    ]
